# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'Networking-Example' do

pod 'AFNetworking', '~> 3.0'

end

target 'Networking-ExampleTests' do

end

target 'Networking-ExampleUITests' do

end

